fail_fast: false
exclude: .git
default_stages: [push, commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: black
        name: Format Python code (black)
        language: system
        types: [python]
        entry: black
  - repo: local
    hooks:
      - id: isort
        name: Correct sort imports (isort)
        language: system
        types: [python]
        entry: isort
        args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: flake8
        name: Check Python code via flake8
        language: system
        types: [python]
        entry: flake8

  - repo: local
    hooks:
      - id: mypy
        stages: [push]
        exclude: package
        name: Check Python code via mypy
        language: system
        types: [python]
        entry: mypy

  - repo: local
    hooks:
      - id: test
        stages: [push]
        name: Checking tests pass
        types: [python]
        language: system
        pass_filenames: false
        entry: pytest
