FROM python:{{ python_version }}

WORKDIR /app

ENV POETRY_VIRTUALENVS_CREATE=0 \
    POETRY_NO_INTERACTION=1

RUN pip3 install poetry==1.3.1

COPY pyproject.toml poetry.lock*

RUN poetry install --only main

COPY . .

EXPOSE {{ port_runOn }}

CMD [ "python", "src/app.py" ]
